/* Auto-generated by generate-uns-dictionary.ts. Do not edit by hand. */
export const GeneratedObjectTypes = {
  /**
   * System-managed: windowed capture/logging outputs. One ObjectId per capture definition; the leaf Table attribute is the table output.
   */
  "capture": "capture",
  /**
   * Maziva, olja, čistila, ki se porabijo in niso del izdelka.
   */
  "consumable-resource": "consumable-resource",
  /**
   * Merilno mesto za aktivno/jalovo energijo in moč.
   */
  "energy-meter": "energy-meter",
  /**
   * Energija (elektrika, para, plin).
   */
  "energy-resource": "energy-resource",
  /**
   * Fizična oprema (stroji, peči, senzorji). Uporablja se za spremljanje stanja, meritev in dogodkov.
   */
  "equipment": "equipment",
  /**
   * Tekočine in plini, ki niso energenti.
   */
  "fluid-resource": "fluid-resource",
  /**
   * Merjenje plina.
   */
  "gas-meter": "gas-meter",
  /**
   * Tracked production material identity.
   */
  "material": "material",
  /**
   * Osebje (operaterji, nadzorniki, tehnologi). Za prisotnost, naloge in status.
   */
  "personnel": "personnel",
  /**
   * Posamezen korak v procesu (npr. valjanje, hlajenje, analiza). Za faze ali aktivnosti procesa.
   */
  "process-segment": "process-segment",
  /**
   * Definicija izdelka, recepture, tehnični opisi. Za metapodatke izdelka in revizije.
   */
  "product-definition": "product-definition",
  /**
   * Kazalniki kakovosti izdelka (odstopanja, ocene, rezultati meritev).
   */
  "product-quality": "product-quality",
  /**
   * Status kateregakoli vira (material, osebje, oprema). Za razpoložljivost, okvare, izrabo.
   */
  "resource-status": "resource-status",
  /**
   * System-managed: outputs of reactive trigger rules. One ObjectId per trigger; one Attribute leaf per fire payload.
   */
  "trigger": "trigger",
  /**
   * Utility viri (voda, zrak, dušik, stisnjeni plini).
   */
  "utility-resource": "utility-resource",
  /**
   * Definicija nalog ali delovnih tokov. Za planirane operacije in navodila.
   */
  "work-definition": "work-definition",
} as const;

export const GeneratedObjectTypeDescriptions: Record<keyof typeof GeneratedObjectTypes, string> = {
  "capture": "System-managed: windowed capture/logging outputs. One ObjectId per capture definition; the leaf Table attribute is the table output.",
  "consumable-resource": "Maziva, olja, čistila, ki se porabijo in niso del izdelka.",
  "energy-meter": "Merilno mesto za aktivno/jalovo energijo in moč.",
  "energy-resource": "Energija (elektrika, para, plin).",
  "equipment": "Fizična oprema (stroji, peči, senzorji). Uporablja se za spremljanje stanja, meritev in dogodkov.",
  "fluid-resource": "Tekočine in plini, ki niso energenti.",
  "gas-meter": "Merjenje plina.",
  "material": "Tracked production material identity.",
  "personnel": "Osebje (operaterji, nadzorniki, tehnologi). Za prisotnost, naloge in status.",
  "process-segment": "Posamezen korak v procesu (npr. valjanje, hlajenje, analiza). Za faze ali aktivnosti procesa.",
  "product-definition": "Definicija izdelka, recepture, tehnični opisi. Za metapodatke izdelka in revizije.",
  "product-quality": "Kazalniki kakovosti izdelka (odstopanja, ocene, rezultati meritev).",
  "resource-status": "Status kateregakoli vira (material, osebje, oprema). Za razpoložljivost, okvare, izrabo.",
  "trigger": "System-managed: outputs of reactive trigger rules. One ObjectId per trigger; one Attribute leaf per fire payload.",
  "utility-resource": "Utility viri (voda, zrak, dušik, stisnjeni plini).",
  "work-definition": "Definicija nalog ali delovnih tokov. Za planirane operacije in navodila.",
};

export type GeneratedObjectTypeName = keyof typeof GeneratedObjectTypes;

export function getGeneratedObjectTypeDescription(name: string): string | undefined {
  return (GeneratedObjectTypeDescriptions as Record<string, string | undefined>)[name];
}

export const GeneratedAttributes = {
  /**
   * Active energy delivered (exported).
   */
  "active-energy-delivered": "active-energy-delivered",
  /**
   * Active energy received (imported).
   */
  "active-energy-received": "active-energy-received",
  /**
   * Alarm.
   */
  "alarm": "alarm",
  /**
   * Assigned to person/team.
   */
  "assigned-to": "assigned-to",
  /**
   * Authorization level.
   */
  "authorization-level": "authorization-level",
  /**
   * Resource availability.
   */
  "availability": "availability",
  /**
   * Batch number.
   */
  "batch-number": "batch-number",
  /**
   * Conductivity.
   */
  "conductivity": "conductivity",
  /**
   * Consumption.
   */
  "consumption": "consumption",
  /**
   * Consumption rate.
   */
  "consumption-rate": "consumption-rate",
  /**
   * Cost.
   */
  "cost": "cost",
  /**
   * Current.
   */
  "current": "current",
  /**
   * Dnevna proizvodnja
   */
  "daily-production": "daily-production",
  /**
   * Deviation from specification.
   */
  "deviation": "deviation",
  /**
   * Downtime.
   */
  "downtime": "downtime",
  /**
   * Duration of phase/task.
   */
  "duration": "duration",
  /**
   * End time.
   */
  "end-time": "end-time",
  /**
   * Energy.
   */
  "energy": "energy",
  /**
   * Energy consumption.
   */
  "energy-consumption": "energy-consumption",
  /**
   * Fault code.
   */
  "fault-code": "fault-code",
  /**
   * Flow.
   */
  "flow": "flow",
  /**
   * Rolling or pushing force.
   */
  "force": "force",
  /**
   * Frequency.
   */
  "frequency": "frequency",
  /**
   * Material hardness.
   */
  "hardness": "hardness",
  /**
   * Inspection result.
   */
  "inspection-result": "inspection-result",
  /**
   * Instruction URL.
   */
  "instruction-url": "instruction-url",
  /**
   * Poraba v časovnem intervalu; ni kumulativno stanje števca.
   */
  "interval-consumption": "interval-consumption",
  /**
   * Last refill.
   */
  "last-refill": "last-refill",
  /**
   * Level in stock/tank.
   */
  "level": "level",
  /**
   * Process-location event for an object, including entered/exited state and event timestamps.
   */
  "location": "location",
  /**
   * Lot identifier.
   */
  "lot-id": "lot-id",
  /**
   * Maintenance status.
   */
  "maintenance-status": "maintenance-status",
  /**
   * Material composition.
   */
  "material-composition": "material-composition",
  /**
   * Material type.
   */
  "material-type": "material-type",
  /**
   * Serijska številka merilne naprave
   */
  "meter-serial-number": "meter-serial-number",
  /**
   * Številka merilnega mesta
   */
  "metering-point-number": "metering-point-number",
  /**
   * Operating hours.
   */
  "operating-hours": "operating-hours",
  /**
   * Operator identifier.
   */
  "operator-id": "operator-id",
  /**
   * Output quantity.
   */
  "output-quantity": "output-quantity",
  /**
   * Oxygen concentration in process or flue gas.
   */
  "oxygen-concentration": "oxygen-concentration",
  /**
   * Pass/fail result.
   */
  "pass-fail": "pass-fail",
  /**
   * pH value.
   */
  "ph": "ph",
  /**
   * Planned end.
   */
  "planned-end": "planned-end",
  /**
   * Planned start.
   */
  "planned-start": "planned-start",
  /**
   * Actuator, valve, or setting position.
   */
  "position": "position",
  /**
   * Power.
   */
  "power": "power",
  /**
   * Personnel presence.
   */
  "presence": "presence",
  /**
   * Pressure.
   */
  "pressure": "pressure",
  /**
   * Previous material identity before the current process-location identifier was assigned.
   */
  "previous-material": "previous-material",
  /**
   * Complete predecessor list for a material merge, encoded in one scalar JSON packet.
   */
  "previous-materials": "previous-materials",
  /**
   * Scalar lifecycle state for an object at a process step.
   */
  "process-state": "process-state",
  /**
   * Product code.
   */
  "product-code": "product-code",
  /**
   * Material quantity.
   */
  "quantity": "quantity",
  /**
   * Reactive energy delivered (exported).
   */
  "reactive-energy-delivered": "reactive-energy-delivered",
  /**
   * Reactive energy received (imported).
   */
  "reactive-energy-received": "reactive-energy-received",
  /**
   * Default Table attribute containing rows emitted by a capture definition.
   */
  "records": "records",
  /**
   * Refill required.
   */
  "refill-required": "refill-required",
  /**
   * Product revision.
   */
  "revision": "revision",
  /**
   * Personnel role.
   */
  "role": "role",
  /**
   * Completed rolling pass event.
   */
  "rolling-pass": "rolling-pass",
  /**
   * Current slot or material position index.
   */
  "slot-index": "slot-index",
  /**
   * Technical specifications.
   */
  "specification": "specification",
  /**
   * Operating speed.
   */
  "speed": "speed",
  /**
   * Start time.
   */
  "start-time": "start-time",
  /**
   * Current status of the resource.
   */
  "status": "status",
  /**
   * Combustion stoichiometric ratio.
   */
  "stoichiometric-ratio": "stoichiometric-ratio",
  /**
   * Surface defect.
   */
  "surface-defect": "surface-defect",
  /**
   * Target parameters.
   */
  "target-parameters": "target-parameters",
  /**
   * Task identifier.
   */
  "task-id": "task-id",
  /**
   * Task list.
   */
  "task-list": "task-list",
  /**
   * Temperature of the resource.
   */
  "temperature": "temperature",
  /**
   * Tensile strength.
   */
  "tensile-strength": "tensile-strength",
  /**
   * Measured material thickness.
   */
  "thickness": "thickness",
  /**
   * Drive or shaft torque.
   */
  "torque": "torque",
  /**
   * Total flow.
   */
  "total-flow": "total-flow",
  /**
   * Resource utilization.
   */
  "utilization": "utilization",
  /**
   * Version history.
   */
  "version-history": "version-history",
  /**
   * Measured vibration.
   */
  "vibration": "vibration",
  /**
   * Voltage.
   */
  "voltage": "voltage",
  /**
   * Work order ID.
   */
  "work-order-id": "work-order-id",
} as const;

export const GeneratedAttributeDescriptions: Record<keyof typeof GeneratedAttributes, string> = {
  "active-energy-delivered": "Active energy delivered (exported).",
  "active-energy-received": "Active energy received (imported).",
  "alarm": "Alarm.",
  "assigned-to": "Assigned to person/team.",
  "authorization-level": "Authorization level.",
  "availability": "Resource availability.",
  "batch-number": "Batch number.",
  "conductivity": "Conductivity.",
  "consumption": "Consumption.",
  "consumption-rate": "Consumption rate.",
  "cost": "Cost.",
  "current": "Current.",
  "daily-production": "Dnevna proizvodnja",
  "deviation": "Deviation from specification.",
  "downtime": "Downtime.",
  "duration": "Duration of phase/task.",
  "end-time": "End time.",
  "energy": "Energy.",
  "energy-consumption": "Energy consumption.",
  "fault-code": "Fault code.",
  "flow": "Flow.",
  "force": "Rolling or pushing force.",
  "frequency": "Frequency.",
  "hardness": "Material hardness.",
  "inspection-result": "Inspection result.",
  "instruction-url": "Instruction URL.",
  "interval-consumption": "Poraba v časovnem intervalu; ni kumulativno stanje števca.",
  "last-refill": "Last refill.",
  "level": "Level in stock/tank.",
  "location": "Process-location event for an object, including entered/exited state and event timestamps.",
  "lot-id": "Lot identifier.",
  "maintenance-status": "Maintenance status.",
  "material-composition": "Material composition.",
  "material-type": "Material type.",
  "meter-serial-number": "Serijska številka merilne naprave",
  "metering-point-number": "Številka merilnega mesta",
  "operating-hours": "Operating hours.",
  "operator-id": "Operator identifier.",
  "output-quantity": "Output quantity.",
  "oxygen-concentration": "Oxygen concentration in process or flue gas.",
  "pass-fail": "Pass/fail result.",
  "ph": "pH value.",
  "planned-end": "Planned end.",
  "planned-start": "Planned start.",
  "position": "Actuator, valve, or setting position.",
  "power": "Power.",
  "presence": "Personnel presence.",
  "pressure": "Pressure.",
  "previous-material": "Previous material identity before the current process-location identifier was assigned.",
  "previous-materials": "Complete predecessor list for a material merge, encoded in one scalar JSON packet.",
  "process-state": "Scalar lifecycle state for an object at a process step.",
  "product-code": "Product code.",
  "quantity": "Material quantity.",
  "reactive-energy-delivered": "Reactive energy delivered (exported).",
  "reactive-energy-received": "Reactive energy received (imported).",
  "records": "Default Table attribute containing rows emitted by a capture definition.",
  "refill-required": "Refill required.",
  "revision": "Product revision.",
  "role": "Personnel role.",
  "rolling-pass": "Completed rolling pass event.",
  "slot-index": "Current slot or material position index.",
  "specification": "Technical specifications.",
  "speed": "Operating speed.",
  "start-time": "Start time.",
  "status": "Current status of the resource.",
  "stoichiometric-ratio": "Combustion stoichiometric ratio.",
  "surface-defect": "Surface defect.",
  "target-parameters": "Target parameters.",
  "task-id": "Task identifier.",
  "task-list": "Task list.",
  "temperature": "Temperature of the resource.",
  "tensile-strength": "Tensile strength.",
  "thickness": "Measured material thickness.",
  "torque": "Drive or shaft torque.",
  "total-flow": "Total flow.",
  "utilization": "Resource utilization.",
  "version-history": "Version history.",
  "vibration": "Measured vibration.",
  "voltage": "Voltage.",
  "work-order-id": "Work order ID.",
};

const GeneratedAttributesByTypeBase = {
  "capture": {
    /**
     * Default Table attribute containing rows emitted by a capture definition.
     */
    "records": "records",
  },
  "consumable-resource": {
    /**
     * Level in stock/tank.
     */
    "level": "level",
    /**
     * Consumption rate.
     */
    "consumption-rate": "consumption-rate",
    /**
     * Refill required.
     */
    "refill-required": "refill-required",
    /**
     * Last refill.
     */
    "last-refill": "last-refill",
    /**
     * Current status of the resource.
     */
    "status": "status",
  },
  "energy-meter": {
    /**
     * Power.
     */
    "power": "power",
    /**
     * Active energy delivered (exported).
     */
    "active-energy-delivered": "active-energy-delivered",
    /**
     * Active energy received (imported).
     */
    "active-energy-received": "active-energy-received",
    /**
     * Reactive energy delivered (exported).
     */
    "reactive-energy-delivered": "reactive-energy-delivered",
    /**
     * Reactive energy received (imported).
     */
    "reactive-energy-received": "reactive-energy-received",
    /**
     * Voltage.
     */
    "voltage": "voltage",
    /**
     * Current.
     */
    "current": "current",
    /**
     * Frequency.
     */
    "frequency": "frequency",
  },
  "energy-resource": {
    /**
     * Power.
     */
    "power": "power",
    /**
     * Energy.
     */
    "energy": "energy",
    /**
     * Active energy delivered (exported).
     */
    "active-energy-delivered": "active-energy-delivered",
    /**
     * Active energy received (imported).
     */
    "active-energy-received": "active-energy-received",
    /**
     * Reactive energy delivered (exported).
     */
    "reactive-energy-delivered": "reactive-energy-delivered",
    /**
     * Reactive energy received (imported).
     */
    "reactive-energy-received": "reactive-energy-received",
    /**
     * Voltage.
     */
    "voltage": "voltage",
    /**
     * Current.
     */
    "current": "current",
    /**
     * Frequency.
     */
    "frequency": "frequency",
    /**
     * Cost.
     */
    "cost": "cost",
  },
  "equipment": {
    /**
     * Current status of the resource.
     */
    "status": "status",
    /**
     * Temperature of the resource.
     */
    "temperature": "temperature",
    /**
     * Measured vibration.
     */
    "vibration": "vibration",
    /**
     * Operating hours.
     */
    "operating-hours": "operating-hours",
    /**
     * Fault code.
     */
    "fault-code": "fault-code",
    /**
     * Operating speed.
     */
    "speed": "speed",
    /**
     * Energy consumption.
     */
    "energy-consumption": "energy-consumption",
    /**
     * Power.
     */
    "power": "power",
    /**
     * Current.
     */
    "current": "current",
    /**
     * Pressure.
     */
    "pressure": "pressure",
    /**
     * Flow.
     */
    "flow": "flow",
    /**
     * Level in stock/tank.
     */
    "level": "level",
    /**
     * Rolling or pushing force.
     */
    "force": "force",
    /**
     * Drive or shaft torque.
     */
    "torque": "torque",
    /**
     * Actuator, valve, or setting position.
     */
    "position": "position",
    /**
     * Current slot or material position index.
     */
    "slot-index": "slot-index",
    /**
     * Output quantity.
     */
    "output-quantity": "output-quantity",
    /**
     * Oxygen concentration in process or flue gas.
     */
    "oxygen-concentration": "oxygen-concentration",
    /**
     * Combustion stoichiometric ratio.
     */
    "stoichiometric-ratio": "stoichiometric-ratio",
  },
  "fluid-resource": {
    /**
     * Flow.
     */
    "flow": "flow",
    /**
     * Pressure.
     */
    "pressure": "pressure",
    /**
     * Temperature of the resource.
     */
    "temperature": "temperature",
    /**
     * Total flow.
     */
    "total-flow": "total-flow",
    /**
     * Level in stock/tank.
     */
    "level": "level",
    /**
     * Consumption.
     */
    "consumption": "consumption",
    /**
     * Current status of the resource.
     */
    "status": "status",
    /**
     * Conductivity.
     */
    "conductivity": "conductivity",
    /**
     * pH value.
     */
    "ph": "ph",
  },
  "gas-meter": {
    /**
     * Consumption.
     */
    "consumption": "consumption",
    /**
     * Consumption rate.
     */
    "consumption-rate": "consumption-rate",
    /**
     * Temperature of the resource.
     */
    "temperature": "temperature",
    /**
     * Serijska številka merilne naprave
     */
    "meter-serial-number": "meter-serial-number",
    /**
     * Številka merilnega mesta
     */
    "metering-point-number": "metering-point-number",
    /**
     * Poraba v časovnem intervalu; ni kumulativno stanje števca.
     */
    "interval-consumption": "interval-consumption",
  },
  "material": {
    /**
     * Process-location event for an object, including entered/exited state and event timestamps.
     */
    "location": "location",
    /**
     * Previous material identity before the current process-location identifier was assigned.
     */
    "previous-material": "previous-material",
    /**
     * Scalar lifecycle state for an object at a process step.
     */
    "process-state": "process-state",
    /**
     * Complete predecessor list for a material merge, encoded in one scalar JSON packet.
     */
    "previous-materials": "previous-materials",
  },
  "personnel": {
    /**
     * Personnel presence.
     */
    "presence": "presence",
    /**
     * Task identifier.
     */
    "task-id": "task-id",
    /**
     * Personnel role.
     */
    "role": "role",
    /**
     * Current status of the resource.
     */
    "status": "status",
  },
  "process-segment": {
    /**
     * Start time.
     */
    "start-time": "start-time",
    /**
     * End time.
     */
    "end-time": "end-time",
    /**
     * Duration of phase/task.
     */
    "duration": "duration",
    /**
     * Current status of the resource.
     */
    "status": "status",
    /**
     * Output quantity.
     */
    "output-quantity": "output-quantity",
  },
  "product-definition": {
    /**
     * Product code.
     */
    "product-code": "product-code",
    /**
     * Product revision.
     */
    "revision": "revision",
    /**
     * Technical specifications.
     */
    "specification": "specification",
    /**
     * Target parameters.
     */
    "target-parameters": "target-parameters",
    /**
     * Material composition.
     */
    "material-composition": "material-composition",
    /**
     * Version history.
     */
    "version-history": "version-history",
  },
  "product-quality": {
    /**
     * Inspection result.
     */
    "inspection-result": "inspection-result",
    /**
     * Deviation from specification.
     */
    "deviation": "deviation",
    /**
     * Pass/fail result.
     */
    "pass-fail": "pass-fail",
    /**
     * Surface defect.
     */
    "surface-defect": "surface-defect",
    /**
     * Material hardness.
     */
    "hardness": "hardness",
    /**
     * Tensile strength.
     */
    "tensile-strength": "tensile-strength",
  },
  "resource-status": {
    /**
     * Resource availability.
     */
    "availability": "availability",
    /**
     * Resource utilization.
     */
    "utilization": "utilization",
    /**
     * Downtime.
     */
    "downtime": "downtime",
    /**
     * Current status of the resource.
     */
    "status": "status",
    /**
     * Maintenance status.
     */
    "maintenance-status": "maintenance-status",
  },
  "trigger": {
    /**
     * Alarm.
     */
    "alarm": "alarm",
  },
  "utility-resource": {
    /**
     * Pressure.
     */
    "pressure": "pressure",
    /**
     * Flow.
     */
    "flow": "flow",
    /**
     * Consumption.
     */
    "consumption": "consumption",
    /**
     * Current status of the resource.
     */
    "status": "status",
    /**
     * Alarm.
     */
    "alarm": "alarm",
  },
  "work-definition": {
    /**
     * Work order ID.
     */
    "work-order-id": "work-order-id",
    /**
     * Task list.
     */
    "task-list": "task-list",
    /**
     * Planned start.
     */
    "planned-start": "planned-start",
    /**
     * Planned end.
     */
    "planned-end": "planned-end",
    /**
     * Assigned to person/team.
     */
    "assigned-to": "assigned-to",
    /**
     * Instruction URL.
     */
    "instruction-url": "instruction-url",
  },
} as const;

export const GeneratedAttributesByType = GeneratedAttributesByTypeBase;

export type GeneratedAttributeName = keyof typeof GeneratedAttributes;

export type GeneratedAttributesFor<T extends keyof typeof GeneratedAttributesByType> = keyof typeof GeneratedAttributesByType[T];

export function getGeneratedAttributeDescription(name: string): string | undefined {
  return (GeneratedAttributeDescriptions as Record<string, string | undefined>)[name];
}
